using Microsoft.EntityFrameworkCore;
using Rankflix.Data.Entities;

namespace Rankflix.Data;

public class RankflixDbContext(DbContextOptions<RankflixDbContext> options) : DbContext(options)
{
    public DbSet<UserEntity> Users => Set<UserEntity>();
    public DbSet<RefreshTokenEntity> RefreshTokens => Set<RefreshTokenEntity>();
    public DbSet<MediaEntity> Media => Set<MediaEntity>();
    public DbSet<RankGroupEntity> RankGroups => Set<RankGroupEntity>();
    public DbSet<RankGroupMemberEntity> RankGroupMembers => Set<RankGroupMemberEntity>();
    public DbSet<RankGroupMediaEntity> RankGroupMedia => Set<RankGroupMediaEntity>();
    public DbSet<RankGroupWatchStatusEntity> RankGroupWatchStatuses => Set<RankGroupWatchStatusEntity>();
    public DbSet<ReviewEntity> Reviews => Set<ReviewEntity>();
    public DbSet<PendingGroupMemberEntity> PendingGroupMembers => Set<PendingGroupMemberEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // gen_random_uuid() is built into Postgres core since v13, but keep this for parity with
        // the old raw-SQL script and in case of an older target database.
        modelBuilder.HasPostgresExtension("pgcrypto");

        modelBuilder.Entity<UserEntity>(e =>
        {
            e.HasKey(u => u.Id);
            e.Property(u => u.Username).HasMaxLength(100);
            e.HasIndex(u => u.Username).IsUnique();
            e.Property(u => u.PasswordHash).HasMaxLength(255);
            e.Property(u => u.DiscordId).HasMaxLength(32);
            e.Property(u => u.Role).HasMaxLength(20).HasDefaultValue("member");
            e.Property(u => u.Status).HasMaxLength(20).HasDefaultValue("online");
            e.Property(u => u.CreatedAt).HasDefaultValueSql("now()");
            e.ToTable(t => t.HasCheckConstraint("ck_user_role", "role in ('admin', 'member')"));
            e.ToTable(t => t.HasCheckConstraint("ck_user_status", "status in ('online', 'invisible')"));
        });

        modelBuilder.Entity<RefreshTokenEntity>(e =>
        {
            e.HasKey(t => t.Value);
            e.Property(t => t.Value).HasDefaultValueSql("gen_random_uuid()");
            e.Property(t => t.CreatedAt).HasDefaultValueSql("now()");
            e.HasIndex(t => t.UserId);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(t => t.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<MediaEntity>(e =>
        {
            e.HasKey(m => m.TmdbId);
            // Explicit ids from TMDB, never generated by the database.
            e.Property(m => m.TmdbId).ValueGeneratedNever();
            e.Property(m => m.Title).HasMaxLength(200);
            e.Property(m => m.Type).HasMaxLength(10);
            e.ToTable(t => t.HasCheckConstraint("ck_media_type", "type in ('movie', 'tv')"));
        });

        modelBuilder.Entity<RankGroupEntity>(e =>
        {
            e.HasKey(g => g.Id);
            e.Property(g => g.Name).HasMaxLength(50);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(g => g.OwnerId).OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<RankGroupMemberEntity>(e =>
        {
            e.HasKey(m => new { m.GroupId, m.UserId });
            e.Property(m => m.IsOwner).HasDefaultValue(false);
            e.HasOne<RankGroupEntity>().WithMany().HasForeignKey(m => m.GroupId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(m => m.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<RankGroupMediaEntity>(e =>
        {
            e.HasKey(m => new { m.MediaId, m.GroupId });
            e.Property(m => m.AddedAt).HasDefaultValueSql("now()");
            e.Property(m => m.VotingDurationHours).HasDefaultValue(24);
            e.HasOne<MediaEntity>().WithMany().HasForeignKey(m => m.MediaId).OnDelete(DeleteBehavior.Restrict);
            e.HasOne<RankGroupEntity>().WithMany().HasForeignKey(m => m.GroupId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(m => m.AddedBy).OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<RankGroupWatchStatusEntity>(e =>
        {
            e.HasKey(w => w.Id);
            e.Property(w => w.Id).HasDefaultValueSql("gen_random_uuid()");
            e.Property(w => w.PendingDiscordId).HasMaxLength(32);
            e.Property(w => w.WatchedAt).HasDefaultValueSql("now()");
            e.HasOne<RankGroupMediaEntity>().WithMany()
                .HasForeignKey(w => new { w.MediaId, w.GroupId })
                .HasPrincipalKey(m => new { m.MediaId, m.GroupId })
                .OnDelete(DeleteBehavior.Cascade);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(w => w.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasIndex(w => new { w.MediaId, w.GroupId, w.UserId }).IsUnique()
                .HasFilter("user_id is not null");
            e.HasIndex(w => new { w.MediaId, w.GroupId, w.PendingDiscordId }).IsUnique()
                .HasFilter("pending_discord_id is not null");
        });

        modelBuilder.Entity<ReviewEntity>(e =>
        {
            e.HasKey(r => r.Id);
            e.Property(r => r.Id).HasDefaultValueSql("gen_random_uuid()");
            e.Property(r => r.CreatedAt).HasDefaultValueSql("now()");
            e.Property(r => r.PendingDiscordId).HasMaxLength(32);
            e.HasOne<RankGroupMediaEntity>().WithMany()
                .HasForeignKey(r => new { r.MediaId, r.GroupId })
                .HasPrincipalKey(m => new { m.MediaId, m.GroupId })
                .OnDelete(DeleteBehavior.Cascade);
            e.HasOne<UserEntity>().WithMany().HasForeignKey(r => r.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasIndex(r => new { r.MediaId, r.GroupId, r.UserId }).IsUnique()
                .HasFilter("user_id is not null");
            e.HasIndex(r => new { r.MediaId, r.GroupId, r.PendingDiscordId }).IsUnique()
                .HasFilter("pending_discord_id is not null");
            e.HasIndex(r => new { r.MediaId, r.GroupId });
        });

        modelBuilder.Entity<PendingGroupMemberEntity>(e =>
        {
            e.HasKey(p => new { p.GroupId, p.DiscordId });
            e.Property(p => p.DiscordId).HasMaxLength(32);
            e.Property(p => p.DisplayName).HasMaxLength(100);
            e.HasOne<RankGroupEntity>().WithMany().HasForeignKey(p => p.GroupId).OnDelete(DeleteBehavior.Cascade);
        });
    }
}
